# Ipython Basic

*Here we will show some basic commands with some magic commands which can be made your life easier in terms of Ipython and Jupyter Notebook*

In [ ]:
#Tab command
#This command show you all the matching variabels names we have typed so far
#This is true for modules too

var1 = 344
var2 = 456
notsimilar = [1,2,3,3,5]



In [ ]:
#now type va and press tab button from your keyboard
#for the list you will find all built in functions . Type notsimilar. and then press Tab from your computer
#This is true for any modules . example pandas . type pd and press Tab . you will find all as a dropdwon
#va
#notsimilar.
#import pandas as pd
#pd.

#uncomment any of variable and press Tab. You will find out



In [ ]:
#Using '?' , you can find information about any variable .
#let us use the previous variables and also define a function and find out info using qeustion mark

def dummy_function(var1,var2):
  return var1//var2

var1?
?var2
notsimilar?
pd?
dummy_function?


In [ ]:
#using this '?' you also can find namespaces for modules like command line
# wildcard charcaters (in between ** ) matched functions will be shown for the modules
#also true for other datastructure . Uncomment notsimilar.*s*? and see
pd.*mer*?
#notsimilar.*s*?

In [ ]:
#you can run any python script within Ipython . using %run command
# To give access your script to any defined variable , you could run %run -i ,
%run your_python_script.py
#If you do not want to run your script but want to import your script , you can use %load magic function
%load your_python_script.py

#want to know more information about %load? okay you know how can we get information,right?

%load?

In [ ]:
#Some keybaord shortcut may help you . Practice and explore

#cltr + c , interrupt your current execution
#cltr + shift + v , paste code from clipboard .


In [ ]:
#some more magic functions
%timeit dummy_function , #will show you the execution time

%pwd #will show you the current dir

%whos #wil show you the variable you have declared so far

#you find information for these magic function using '?', right ?
#Also you can find all the magic function available with documentation using just %magic

%magic



72.6 ns ± 20.5 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
Variable         Type        Data/Info
--------------------------------------
dummy_function   function    <function dummy_function at 0x7974dd8203a0>
notsimilar       int         9
pd               module      <module 'pandas' from '/u<...>ages/pandas/__init__.py'>
var1             int         344
var2             int         456


# Numpy Basics

In [ ]:
# Numpy is stand for Numerical Python
#Fist a demo will show us why we should use Numpy
import numpy as np

#define a np array
nparray = np.arange(100)
#define a python list
lst = list(range(100))

print(type(nparray))
print(type(lst))

#Now we will check their wall time for some operations

%time for _ in range(len(nparray)): result = nparray * 2

%time for _ in range(len(lst)): r = [x * 2 for x in lst]

# You will find numpy array with better performance in terms of time.

<class 'numpy.ndarray'>
<class 'list'>
CPU times: user 393 µs, sys: 0 ns, total: 393 µs
Wall time: 2.18 ms
CPU times: user 536 µs, sys: 0 ns, total: 536 µs
Wall time: 537 µs


In [ ]:
# Uisng numpy array you can define N-dimensional array

#1D array
arr1 = np.arange(10)
print('1D Array ')
print(arr1)
print(arr1.shape)

#2D array
arr2 = np.random.randn(3,2)
print('2D Array ')
print(arr2)
print(arr2.shape)

#3D array
arr3 = np.random.randn(4,3,2)
print('3D Array ')
print(arr3)
print(arr3.shape)

#4D array
arr4 = np.random.randn(5,4,3,2)
print('4D Array ')
print(arr4)
print(arr4.shape)

#you can check data type of an array using dtype , Type arr1.dtype() and see

1D Array 
[0 1 2 3 4 5 6 7 8 9]
(10,)
2D Array 
[[ 1.56473614  0.21202945]
 [ 0.6831668  -0.50646289]
 [-0.08517581  0.2250628 ]]
(3, 2)
3D Array 
[[[-0.72850396  0.79585351]
  [ 0.33920587 -0.48008963]
  [ 0.6758638   0.06636951]]

 [[-1.23443556  0.6719073 ]
  [ 0.31032829 -0.10468677]
  [-0.35557524 -0.31892691]]

 [[ 0.65325038 -0.13799017]
  [ 0.93087147 -0.14495911]
  [ 2.60688667  0.34735332]]

 [[ 0.11496473  0.67467153]
  [ 1.0907255  -0.88232212]
  [-0.30188783 -0.14049868]]]
(4, 3, 2)
4D Array 
[[[[ 0.28091772  0.49383041]
   [-1.46296584 -0.89591902]
   [ 0.84343695  1.17518362]]

  [[ 0.89951307 -1.07658134]
   [-0.10427918  0.8139988 ]
   [-0.79530737  0.85478465]]

  [[ 1.02341462  0.21911469]
   [ 0.09047287  1.36967806]
   [-1.57493579 -1.49283398]]

  [[-1.13299773  2.21857176]
   [-1.14189496 -0.69633676]
   [ 0.21092482  0.97509139]]]


 [[[-1.98615194  0.79769891]
   [ 0.35610485 -0.58932572]
   [-0.23067952 -0.49968972]]

  [[ 0.92129964  0.31523072]
   [-0.917964

In [ ]:
#we can covert any sequence to numpy array using np.array() function

data = [1,4,5,67,90,8.9]
print(data)
print(type(data))
data_array = np.array(data)
print(data_array)
print(type(data_array))
print(data_array.dtype)

# You also can pass a list of list . LIke bellow . Uncomment the code and run
'''
data2 = [[1,4,0.6],[2,8,9.6]]
print(data2)
data2_array = np.array(data2)
print(data2_array)
'''

# Additionally you can explore dimension using dim function and shape using shape function . like ,

'''
print(data2_array.dim)
print(data2_array.shpae)
'''

[1, 4, 5, 67, 90, 8.9]
<class 'list'>
[ 1.   4.   5.  67.  90.   8.9]
<class 'numpy.ndarray'>
float64


'\nprint(data2_array.dim)\nprint(data2_array.shpae)\n'

In [ ]:
#Some other function to create numpy array

new_array = np.asarray(data) #convert sequence as array and stores in a new memory location . Hence any change in data will not affect new_array

new_array_2 = np.asarray(data_array) # As data_array is already an array, new_array_2 will  just refer the memory location of data_array. Hence any change in data_array will reflect in new_array_2
print(new_array_2)
print('------')

'''
#uncomment this block and see the difference

data.insert(2,440)
print(data)
print('----')

print(new_array)

data_array[4] = 80

print(data_array)
print('--------')
print(new_array_2)
'''

[ 1.   4.   5.  67.  90.   8.9]
------


"\n#uncomment this block and see the difference \n\ndata.insert(2,440)\nprint(data)\nprint('----')\n\nprint(new_array)\n\ndata_array[4] = 80\n\nprint(data_array)\nprint('--------')\nprint(new_array_2)\n"

In [ ]:
#Some other fucnton to create numpy array
#np.arange , will create an numpy array with your defined range. Buitl in it will start from 0 . it is as same as range funtion but it will return an numpy array

arange_array = np.arange(1,10,dtype = np.float32) #you can assign any valid data type
print(arange_array)
print(arange_array.dtype)

#you can also change data type
arange_array = arange_array.astype('int32')
print(arange_array.dtype)

#also you can reshape your array. as 9 elements , we can reshape with 3,3 array
arange_array.reshape(3,3)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
float32
int32


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [ ]:
#Some other functions to create numpy array

ones = np.ones((3,3))
print( ones)



#ones_like take an array and creates an ones array with the same shape of input array

ones_lk = np.ones_like(ones) #change ones shape and you will find ones_lk will be generated with same shape as ones


'''
#similarly you can use these funcions and can see what happend . Uncomment and run

zeros = np.zeros((4,4))
zeros_lk = np.zeros_like(ones)
emp = np.empty((3,3))          # will allocate memory but will not assign any value
emp_lk = np.empty_like(ones)   # create memory as shape of ones but will not populated any value




'''

full = np.full((3,3),fill_value = 5) #very similar with ones and zeros but instead one or zero value , we can pass a fill value
print(full)

eye = np.identity(4)   #create an n * n array, fill the diagonal with 1's and rest postions are filled with 0. you also can try np.eye , instead np.identity .
print(eye)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#you can perform any arithmetic operations in numpy array
#Operations will be elementwise . Means perform in every postion without looping explicity

nar = np.array([[2,4,6],[8,10,12]])
print(nar)

# we can do any arithmetic operation . let's assume a division with 2 . we will use //  operator to return int value .

print(nar // 2)

# we can multiply with the array itself

print(nar * nar)

print(nar ** 3) # we can qube every element

print((nar ** 3) > (nar * nar)) # Even we can return any boolean array using logics


# See the operation is element-wise

[[ 2  4  6]
 [ 8 10 12]]
[[1 2 3]
 [4 5 6]]
[[  4  16  36]
 [ 64 100 144]]
[[   8   64  216]
 [ 512 1000 1728]]
[[ True  True  True]
 [ True  True  True]]


In [ ]:
#array indexing and slicing
# array indexing is quite easy . Let's try with our 2d array

print('Second row of nar array with every columns')
print(nar[1]) #print nar's second element . in this case it is the second row . As nar contains two rows , each row has 3 columns

#if you want to access first row , third column
print('First row, third column . Return as a single value')
print(nar[0][2])

print('syntax is diffrent but do the same')
print(nar[0,2]) # or you can use this syntax

#if you want to selct only first two colums of each row

print('Every row, Only first two  columns')
print(nar[:,:2])

#if you want only one columns of first row

print('Fist row ,First column . But return as a array')
print(nar[:1,:1])

# - sign will select column in reverse sequence of columns . so will do for rows . Like 0 is for the first index , -1 is indicating first in reverse order , that means the last element.
print('only the last column of last row of nar')
print(nar[-1,-1])


#important thing is this slicing is not create a new array . Instead it is reffering the memory location of our original nar var . so any change will change our main nar array

#select a range like first two columns of each row

sliced_nar = nar[:,:2]
print('Slicig nar array with each row and first two columns')
print(sliced_nar)

#insert a value in second row , second column

sliced_nar[1,1] = 445

#if we print our nar , we can see the change


print ('As we have changed our sliced_nar array , this will reflect our main array nar:')
print(nar)


'''
#so if you need to make a copy means same data in different memory location , you can use np.copy function . any change in copied array will not affect nar or sliced_nar

d_array = sliced_nar.copy()

d_array[1,0] = 456

print(d_array)

print('-----')

print(sliced_nar)

print(nar)

'''



Second row of nar array with every columns
[ 8 10 12]
First row, third column . Return as a single value
6
syntax is diffrent but do the same
6
Every row, Only first two  columns
[[ 2  4]
 [ 8 10]]
Fist row ,First column . But return as a array
[[2]]
only the last column of last row of nar
12
Slicig nar array with each row and first two columns
[[ 2  4]
 [ 8 10]]
As we have changed our sliced_nar array , this will reflect our main array nar:
[[  2   4   6]
 [  8 445  12]]


"\n#so if you need to make a copy means same data in different memory location , you can use np.copy function . any change in copied array will not affect nar or sliced_nar\n\nd_array = sliced_nar.copy()\n\nd_array[1,0] = 456\n\nprint(d_array)\n\nprint('-----')\n\nprint(sliced_nar)\n\nprint(nar)\n\n"

In [ ]:
#Some other Indexing

#Boolean indexing . you can filter out your numpy array with a boolean array . where each only rows of numpy array for True indexs of boolean array

bool_array = [True , True, False ,False , False ,True ,False]
ln = len(bool_array)

data_array = np.random.randn(ln,3)
print('boolean array')
print(bool_array)
print('data array ')
print(data_array)

print('filtering data array rows with bool_array')
print(data_array[bool_array]) #retunring only those rows number , which are same as the True value index of bool_array. 0,1,5 indexes are True in bool_array.so data_array only returns 0,1 and  5th rows
print('even you can slicing the filtered array. Only first two columns of filered array')
print(data_array[bool_array,:2])



#you can indexing your array in  some fancy way
#first create an empty array and add some value using for loop

fan_array = np.empty((6,3),dtype = 'int16')
for i in range(len(fan_array)):
  fan_array[i] = i


print('created a 2D array with some values')
print(fan_array)

print('we can rearranging index of our array . Like the order will be like 2th,4th,0th,6th rows respectively ')
print(fan_array[[2,4,0,5]]) # we can pass the index ordering regarding our rows of the array. Means we can tell the indexing order .

print('Even with columns')
print(fan_array[[2,4,0,5]][:,[2,0,1]]) #we have rearranged the columns position too

print('We can select row:column postiton too')
print('we have picked here "third row : second column" , "first row : third collumn and fourth row : first column" pairs ')
print(fan_array[[2,0,3],[1,2,0]])


boolean array
[True, True, False, False, False, True, False]
data array 
[[ 1.69323441 -0.65475263  0.78617622]
 [ 0.17587661  2.40917047  0.16297645]
 [ 0.33106249 -0.38417329  1.28650094]
 [ 0.10006448  2.26351511  0.93217582]
 [-0.1398946  -0.03265628  0.10454997]
 [-0.70030259  0.39167495 -0.14689271]
 [ 1.57646744  1.06540757 -1.12112745]]
filtering data array rows with bool_array
[[ 1.69323441 -0.65475263  0.78617622]
 [ 0.17587661  2.40917047  0.16297645]
 [-0.70030259  0.39167495 -0.14689271]]
even you can slicing the filtered array. Only first two columns of filered array
[[ 1.69323441 -0.65475263]
 [ 0.17587661  2.40917047]
 [-0.70030259  0.39167495]]
created a 2D array with some values
[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]
 [5 5 5]]
we can rearranging index of our array . Like the order will be like 2th,4th,0th,6th rows respectively 
[[2 2 2]
 [4 4 4]
 [0 0 0]
 [5 5 5]]
Even with columns
[[2 2 2]
 [4 4 4]
 [0 0 0]
 [5 5 5]]
We can select row:column postiton too
we hav

In [ ]:
#Numpy array reshaping using Transpose , .T and swapaxes functions

#Fist .T . which will make row into columns and columns into row .
# If a position has index [1,0] it will become [0,1]
# For 3D it will change postion [0,0,1] with [1,0,0] . It will just swap the first and last axis . middle axis will be unchanged


print('our fan array is like ')
print(fan_array)
print('shape of the array is' + str(fan_array.shape))
print('Transposing our fan_array using .T function')
print(fan_array.T)
print('Shape after transposing is ' + str((fan_array.T).shape))


#You can transpose array using .transpose function . you have to pass the axis order
#if we have a 3D array and if we pass order as (1,0,2) . For the reshaped array the first axis will be input array's second axis , second will be input array's first axis and third will be input array's third axis
# so for the order , the position of [0,1,0] will be [1,0,0]

ar = np.array([[[1,2,3],[3,4,5]],[[3,7,9],[8,5,4]]])
print('Our 3D array is')
print(ar)
print('shape of the array is ')
print(ar.shape)
print('After transposing using transpose(1,0,2)')
print(ar.transpose(1,0,2))
print('new shape is ')
print(ar.transpose(1,0,2).shape)

print('find [0,1,0] position of ar and you wil find the value in [1,0,0] position of our reshaped array')


#You also can reshpae numpy array with swapaxes fucntion . But with this only two axis at a time.
#swapaxes(0,2) , where dimension between 0 axis and 2 axis will be interchanged
#so consider a position [0,0,1] will become [1,0,0] , inter changing first and last axis

print('Our 3D array is ')
print(ar)
print('Our 3D array shape is ' + str(ar.shape))
print('After swapping our first and third axis using swap axes')
print(ar.swapaxes(0,2))
print('after swapping with swapaxes function now the array shape is ' + str((ar.swapaxes(0,2).shape)))




our fan array is like 
[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]
 [5 5 5]]
shape of the array is(6, 3)
Transposing our fan_array using .T function
[[0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]]
Shape after transposing is (3, 6)
Our 3D array is
[[[1 2 3]
  [3 4 5]]

 [[3 7 9]
  [8 5 4]]]
shape of the array is 
(2, 2, 3)
After transposing using transpose(1,0,2)
[[[1 2 3]
  [3 7 9]]

 [[3 4 5]
  [8 5 4]]]
new shape is 
(2, 2, 3)
find [0,1,0] position of ar and you wil find the value in [1,0,0] position of our reshaped array
Our 3D array is 
[[[1 2 3]
  [3 4 5]]

 [[3 7 9]
  [8 5 4]]]
Our 3D array shape is (2, 2, 3)
After swapping our first and third axis using swap axes
[[[1 3]
  [3 8]]

 [[2 7]
  [4 5]]

 [[3 9]
  [5 4]]]
after swapping with swapaxes function now the array shape is (3, 2, 2)


In [ ]:
#Some basic element-wise function in Numpy

x = np.random.randn(5)
y = np.random.randn(5) * 7
np.sqrt(ar) #calclualte sqrt of each element
np.exp(ar) #calculate exponential of each element
np.maximum(x,y) #will take same length array x and y and return the maximum values after elementwise comparing
reminder , whole = np.modf(y) #return whole and reminder parts as array. you can unpack them using two variables
np.square(ar) #calcualte the squeare value of each element of given array ar
np.abs(x)  #retrun abs value , you can also use np.fabs()
np.log(ar) # calculate log of each element as base e . you can use np.log10,np.log2 , np.logP for base 10,2 and calculate log(1+x) respectively
#print(x)
np.ceil(x) #compute ceiling
np.floor(x) #comupute floor
np.rint(x) #do not change the dtype but round the number to the nearest int
np.isnan(x)  #return a boolean array . if  element is NaN , return true else return false
np.isfinite(x) #return a boolean array . If element is finite put true on that index , else false
np.isinf(x) # retrun a boolean array  .If element is infinite value put true on that index , else false
np.add(x,y) #add to array . similarly np.subtract(x,y) will perform x - y .similarly multiply,divide and floor_divide . you  can try using
np.power(y,x) #this will perform element wise y ** x
np.fmax(x,y)  # similar as np.maximum but ignores NaN . You also can use np.minimum or np.fmin. why don't extract info about functions about putting ?
#np.mod(x) #calculate element-wise modulus .


'''
#these are some additional numpy functions . you should also try these

#Regular and hyperbolic trigonometric functions
np.cos(), np.cosh(), np.sin(),
np.sinh(), np.tan(), np.tanh()

#Inverse trigonometric functions
np.arccos(), np.arccosh(),
np.arcsin(), np.arcsinh(),
np.arctan(), np.arctanh()

Compute truth value of not x element-wise (equivalent to ~arr).
np.logical_not()

#Compute element-wise truth value of logical operation (equivalent to infix operators & |, ^)
np.logical_and()
np.logical_or()
np.logical_xor()

similarly for elementwise comparision here are some built in functions

np.greater()
np.greater_equal()  #Perform element-wise comparison, yielding boolean array (equivalent to infixoperators >, >=, <, <=, ==, !=)
np.less(),
np.less_equal(),
np.equal()
np.not_equal()


'''
#Read details using question marks after or before these function

<ipython-input-42-bb457d6b7fc8>:20: RuntimeWarning: invalid value encountered in power
  np.power(y,x) #this will perform element wise y ** x


'\n#these are some additional numpy functions . you should also try these\n\n#Regular and hyperbolic trigonometric functions\nnp.cos(), np.cosh(), np.sin(),\nnp.sinh(), np.tan(), np.tanh()\n\n#Inverse trigonometric functions\nnp.arccos(), np.arccosh(),\nnp.arcsin(), np.arcsinh(),\nnp.arctan(), np.arctanh()\n\nCompute truth value of not x element-wise (equivalent to ~arr).\nnp.logical_not()\n\n#Compute element-wise truth value of logical operation (equivalent to infix operators & |, ^)\nnp.logical_and()\nnp.logical_or() \nnp.logical_xor()\n\nsimilarly for elementwise comparision here are some built in functions\n\nnp.greater()\nnp.greater_equal()  #Perform element-wise comparison, yielding boolean array (equivalent to infixoperators >, >=, <, <=, ==, !=)\nnp.less(), \nnp.less_equal(),\nnp.equal()\nnp.not_equal()\n\n\n'

In [ ]:
#conditional_logics on Numpy array
#you can use np.where which will save from looping
#convention is np.where(logic, value, else_value)
arr1 = np.random.randint(1,10,size = (3,4)) #an array of shape (3,4), values will be range between 1-10
np.where(arr1 > 5 , 0, arr1) #this is a element wise logic operation using np.where() . where element greater than 5 ,put a 0 else the element will be unchanged



array([[4, 0, 0, 2],
       [3, 1, 1, 0],
       [2, 0, 0, 4]])

In [ ]:
#Statistical methods
#you can use mean or sum or cumilitive sum axis wise
print(arr1)
#if you want to sum of an array you can use np.sum() . The operation will be element-wise
arr1.sum() #or you can use np.sum(arr1) # This will give you the total sum  of every elements in your array
print('sum of arr1 is : ' + str(arr1.sum()))

#Or you can sum element column-wise using axis = 1
print('total of each row , means sum of col1 + col2 + col3 + col4 for each row : '+str(arr1.sum(axis = 1)))

print('total of each column means row1 + row2 + row3 for each column is : '+str(arr1.sum(axis = 0))) #using axis = 0 will be do operation row wise

#similary you can calculate mean using np.mean(),
print('mean of arr1 is : ' + str(arr1.mean()))
print('Column-wise mean' + str(arr1.mean(axis = 1)))
print('row-wise mean' + str(arr1.mean(axis = 0)))

[[4 6 8 2]
 [3 1 1 6]
 [2 6 7 4]]
sum of arr1 is : 50
total of each row , means sum of col1 + col2 + col3 + col4 for each row : [20 11 19]
total of each column means row1 + row2 + row3 for each column is : [ 9 13 16 12]
mean of arr1 is : 4.166666666666667
Column-wise mean[5.   2.75 4.75]
row-wise mean[3.         4.33333333 5.33333333 4.        ]


In [ ]:
#Some more statistical methods for Numpy
print('cumulative sum of arr1 is : ' + str(arr1.cumsum())) # the first value of output array is (0,0) of input array , next value is (0,0) + (0,1) , next one is (0,0) + (0,1) + (0,2) and keep repeating until last element of input array
print('cumulative sum of arr1 via column is : ' + str(arr1.cumsum(axis = 1))) # for each row it will be like col1 , col1 + col2 , col1 + col2 + col3, col1 + col2 + col3 + col4
print('cumulative sum of arr via row is ' + str(arr1.cumsum(axis = 0)) ) # for each column it will be like row1 , row1 + row2 , row1 + row2 + row3

#i will left all the other functions for your practice . Do not skip

#np.cumprod() #To calculate cumulative production . Try with axis 1 and 0
#np.std()  #To calculate std. deviation
#np.var() #To calculate variance
#np.max() #return the maximum value
#np.min() #return the minimum value
#np.argmax() #return the maximum value's index
#np.argmin() #return the minimum value's index
#boolean array Methods
#np.any() #return true if any elmenet is true of a boolean array .
#np.all() #return true if all the elements are true in a boolean array
#np.array(bool_array).all()


cumulative sum of arr1 is : [ 4 10 18 20 23 24 25 31 33 39 46 50]
cumulative sum of arr1 via column is : [[ 4 10 18 20]
 [ 3  4  5 11]
 [ 2  8 15 19]]
cumulative sum of arr via row is [[ 4  6  8  2]
 [ 7  7  9  8]
 [ 9 13 16 12]]


False

In [ ]:
#Sorting Numpy arrays
#quite easy . like built-in list , you can call sort() function .
#also you can pass axis to sort row or columns only for multi-dimensional arrays

arr1.sort() #pass axis = 0 or 1 in the method and check what will happen
arr1


array([[2, 4, 6, 8],
       [1, 1, 3, 6],
       [2, 4, 6, 7]])

In [ ]:
#Some set operation

# unique is quite usefull function to find out unique values
np.unique(arr1) #return the unique values in a sorted array

# To find similar values between two array . we can use intersect1d()
# we will need to pass two arrays and it will return a sorted array with common values

j = np.random.randint(10,size = 10)
k = np.random.randint(10,size = 10)

print('first array : ' + str(j))
print('second array : ' + str(k))
print('unique values of j :' + str(np.unique(j)))
print('sorted common values : '+ str(np.intersect1d(j,k)))

#To find the values that are not common between two array , we can use setxor1d()

print('sorted uncommon values are : ' + str(np.setxor1d(j,k)))

#To find values of j that are not prsent in k . Do not get confused with uncommon values. uncommon values are those which are present either array not in both
print('values that are present in j array but not in k array : ' + str(np.setdiff1d(j,k)))

#to find a boolean array if element of one array is present in other
print('boolean array if the element of j is present in k ' + str(np.in1d(j,k)))

#To create a sorted array with the both elements of both arrays with unique values only
print('Union of j and k is  : ' +str(np.union1d(j,k)))

first array : [9 2 6 6 7 2 6 3 6 1]
second array : [1 4 9 3 9 6 2 2 3 4]
unique values of j :[1 2 3 6 7 9]
sorted common values : [1 2 3 6 9]
sorted uncommon values are : [4 7]
values that are present in j array but not in k array : [7]
boolean array if the element of j is present in k [ True  True  True  True False  True  True  True  True  True]
Union of j and k is  : [1 2 3 4 6 7 9]


In [ ]:
#Save and import your saved Numpy array

#to save
np.save('arr.npy',arr1) # np.save(filepath_where_want_to_save,array_to_be_saved)

#to import your saved numpy array , use load function
np.load('arr.npy') #np.load(file_path)

#you can save multiple array in a single file also using np.savez() funciton

np.savez('archive.npz',a = arr1 , b = j , c = k) #np.savez(filepath, key_argunent = array) . each array as a separate key_argument

#to load multiple array use same load function

archive = np.load('archive.npz')

archive['a']  #use the key argument to acess the specific array




array([[2, 4, 6, 8],
       [1, 1, 3, 6],
       [2, 4, 6, 7]])

In [ ]:
#Numpy array linear algebric functions
#Numpy has linalg module for matrix operation
#np.linalg?

mat = np.random.randint(1,20 , size = (4,4))
print('Our matrix is : \n' + str(mat))

#to inverse use inv() function
print('inverse of our matrix is : \n' + str(np.linalg.inv(mat)))

#To return the diagonal values we can use diag() function, also we can covert a 1d array to square matrix using this function
print('Diagoanal values of our matrix is : \n' + str(np.diag(mat)))

d = np.array([2,4,6,8])
print('Square matrix using 2,4,6,8 as diagonal value : \n' + str(np.diag(d)))


#to create the sum of the diagonal value we can use trace() function

print('sum of the diagonal values of matrix mat is : {}  '. format(np.trace(mat)))



#compute the matrix determinant
print(f"determinat of our matrix is : {np.linalg.det(mat)}")


Our matrix is : 
[[ 2  6 18 11]
 [ 3 10  5  6]
 [15 17  1  1]
 [ 8  2  2 19]]
inverse of our matrix is : 
[[ 0.03877831 -0.16609472  0.08098833  0.02573782]
 [-0.03749922  0.14693954 -0.01154302 -0.02408436]
 [ 0.07621514 -0.06819742  0.01597305 -0.02342921]
 [-0.02040307  0.06164597 -0.03456667  0.04679603]]
Diagoanal values of our matrix is : 
[ 2 10  1 19]
Square matrix using 2,4,6,8 as diagonal value : 
[[2 0 0 0]
 [0 4 0 0]
 [0 0 6 0]
 [0 0 0 8]]
sum of the diagonal values of matrix mat is : 32  
determinat of our matrix is : -32054.000000000004


In [ ]:
#Some additional fucntions

#solve() , method used to solve linear equations using matrix as Ax = b, where A is a square matrix and b could be matrix or vector(1d array)
#consider an exmaple

'''
 6x + 4y = 18
 36x + 32y = 148

 now we will solve our equation using solve()



'''
A = np.array([[6,4],[36,32]])
B = np.array([18,148])

print(f"our A is \n {A} ")
print(f"B is \n {B}")
print(f'Using solve our x and y values are " {np.linalg.solve(A,B)}')

#But what if our matrix is not squeare ? Then we will use another function to solve our equation
# we will use lstsq, least square approach to solve the equation
# consider another example

'''
 6x + 4y = 18
 36x + 32y = 148
 5x + 24y = 98

 now we will solve our equation using solve()



'''
a = np.array([[6,4],[36,32],[5,24]])
b = np.array([18,148,98])

print(f"our A is \n {a} ")
print(f"B is \n {b}")
#print(f'Using least square our x and y values are " {np.linalg.lstsq(a,b)}')
x ,residuals,rank,s = np.linalg.lstsq(a,b,rcond = None)
print("Least squares solution for x and y:", x)
print("Residuals:", residuals)
print("Rank of matrix A:", rank)
print("Singular values of A:", s)

our A is 
 [[ 6  4]
 [36 32]] 
B is 
 [ 18 148]
Using solve our x and y values are " [-0.33333333  5.        ]
our A is 
 [[ 6  4]
 [36 32]
 [ 5 24]] 
B is 
 [ 18 148  98]
Least squares solution for x and y: [0.57872261 3.966569  ]
Residuals: [1.8558025]
Rank of matrix A: 2
Singular values of A: [52.81054756 13.56635788]


In [ ]:
#some other functions like qr,svd and eig

#QR decomposition. you can calculate matrix qr decomposition usign qr function
# like a matrix a = qr ,where a should be square matrix

'''
a =qr
q is an orthogonal (or unitary) matrix (its columns are orthonormal, meaning qTq = I)
r is an upper triangular matrix (all elements below the main diagonal are zero).
'''

q, r = np.linalg.qr(a)
print(f'using solve q is \n{q} \n and r is \n {q} \n ')


#To calculate single valued decomposition we will use svd()
#consider the bellow exmaple

'''
Singular Value Decomposition (SVD) is a more general matrix decomposition that applies to any m*n matrix (not necessarily square). It factors matrix
A into three matrices: A=UΣV^T

where ,
  U is an m*m orthogonal matrix (its columns are called the left singular vectors of A),
  Σ is an m*n diagonal matrix whose diagonal elements are the singular values of A,
  V^T is an n*n orthogonal matrix (its columns are the right singular vectors of A).

'''

U,sigma,V = np.linalg.svd(a)
print(f"using svd , U is \n {U} \n  \n sigma is {sigma} \n and V^T is \n {V}")


#To get eigenvectors and eigenvalues we can use eig() function

'''
Eigendecomposition is a factorization of a square matrix into its eigenvalues and eigenvectors. It is a fundamental concept in linear algebra and is useful in various fields such as data science, machine learning, and quantum physics.

For a given square matrix A, if there exists a vector v (called an eigenvector) and a scalar λ (called an eigenvalue) such that:

A v = λ v
'''

eigenvalues, eigenvectors = np.linalg.eig(A)
print(f"Using eigenvalues  and eigenvectors for our square matrix \n {A} \n the eigenvalue is {eigenvalues} and the eigenvector is \n {eigenvectors} ")

using solve q is 
[[-0.16287759 -0.08896603]
 [-0.97726552 -0.12246091]
 [-0.13573132  0.9884778 ]] 
 and r is 
 [[-0.16287759 -0.08896603]
 [-0.97726552 -0.12246091]
 [-0.13573132  0.9884778 ]] 
 
using svd , U is 
 [[-0.13239608 -0.13005899 -0.98262706]
 [-0.90669145 -0.38464943  0.17307636]
 [-0.40047708  0.91385418 -0.0669973 ]] 
  
 sigma is [52.81054756 13.56635788] 
 and V^T is 
 [[-0.67103364 -0.7414269 ]
 [-0.7414269   0.67103364]]
Using eigenvalues  and eigenvectors for our square matrix 
 [[ 6  4]
 [36 32]] 
 the eigenvalue is [ 1.30819399 36.69180601] and the eigenvector is 
 [[-0.64877435 -0.12923501]
 [ 0.76098085 -0.99161399]] 


# Pandas Basics


*Read every comment and run every line to see changes . or Maybe comment unnecssary lines and run . I did not create a cell for each functions or operations to reduce cell numbers . But you must explore*

In [1]:
#pandas is toolkit for making data analysis easy and handy
#pandas has two structure , series and dataframe
#series can be thouhgt as 1d array with index . so you can think like a fixed dimensional dict also
#data frame is on the other hand 2d array with indexs(row and column) and header with different dtype

import pandas as pd
import numpy as np

#to create series
series = pd.Series([-4,4,5,6,7])
series
#you can also passs index values by your ownn with index param or can pass a dict

series = pd.Series({'one': 6,'two ': 7 , 'three ': 9})
series

#or you can pass index

series = pd.Series([1,5,7,89,0,4,3],index = np.arange(7))
series

0     1
1     5
2     7
3    89
4     0
5     4
6     3
dtype: int64

In [2]:
#you can call dataframe using DataFrame() function

df = pd.DataFrame(np.random.randint(100,size = (5,5)),columns = ['col1','col2','col3','col4','col5'])
df

#or you can pass dict with or without your custom index

dict_data = {'country':['Ban','Ind','SL','NPL','UK','Fr'],
             'capital': ['Dhaka','Delhi','Colombo','Kathmundu','London','Paris'],
             'status': ['postivie','negative','positive','positive','negative','negative'],
             'code': [1,2,3,4,5,6]}

df = pd.DataFrame(dict_data,index = ['a','b','c','d','e','f'])
df

country    capital    status  code
a     Ban      Dhaka  postivie     1
b     Ind      Delhi  negative     2
c      SL    Colombo  positive     3
d     NPL  Kathmundu  positive     4
e      UK     London  negative     5
f      Fr      Paris  negative     6

In [3]:
#you can show top or bottom rows usng haead or tail

df.head() #give you top-5 rows . you can specify row number by passig the number as an argument like df.head(10)
df.tail() #give you bottom-5 rows . you can specify row number by passsing the number as an argument like df.tail(number)

#you can access column either as dict or attribut notation and retrieved as a series
df['capital'] #or
df.capital

#you can also access row using .loc() . you can pass index number via loc()

df.loc['f']

#you can also use iloc to access using number instead of index name and column names
#like if you want to access fourth row second column you can access using .iloc(row_number,column_number)
#or you can also simply select whole row using .ilolc[row_number]
#You can also try slicing here like we did in Numpy. Give it a try

df.iloc[3,1]

#you can create a new column simply define the column.

df['new_column'] = np.random.randn(6) #you can put a sequenc value or scalar or boolearn
#or
df['another_new_column'] = 3 #scalar value
#or
df['boolean_new_value'] = df.status == 'positive' #boolean value



#you can delete a column by using del() function
print(f'datafame df has columns : {df.columns.to_list()} before delete a columm ')
del df['new_column']
print(f'dataframe df column names after deleting new_column : {df.columns.to_list()}')

#to insert a row earlier pandas has an append function but now you have to use concat function . But inserted row must be a series or dataframe
row =pd.Series({'country':'Can','capital':'Toronto','status':'positive'})
print(pd.concat([df,row]))


#to delete a row use df.drop(index_name)
df.drop('a')

#you can also drop columns using drop(column_name,axis = 1) axis = 1 always tell to operations column-wise. Even you can pass a list of column names
df.drop('code',axis = 1) #this will drop code column with its values




#By the way you can even name your columns and indexs like
df.index.name = 'Index'
df.columns.name = 'Columns'

df


# you can also traspose your dataframe like numpy

df.T

#Index are immutable hence you can change index value like index[1] = 'some_value' , you will get an error . you can try though

#Some index functionality
df.index.unique() #you can get unique index value. Index value can be duplicate too
df.index.is_unique #to check your index has duplicate or not
df.index.isin(['a','l']) #you can check whether a value of list or sequence isin matches with your index . you will get a boolean array .
df.index.drop('a') #to delete row at mentioned index . mind it , if you do not set inplace = True, it will not modify your original dataframe as these always shows you a copy
#df.index.append?
df.index.union(np.array(['l','m']))
#similarly uncommet fucntions bellow and check documentation using ? and implement . do not sikp
#df.index.different()
#df.index.delete()
#df.index.intersection()
#Using <Tab> see all available function and practice . DO NOT SKIP




datafame df has columns : ['country', 'capital', 'status', 'code', 'new_column', 'another_new_column', 'boolean_new_value'] before delete a columm 
dataframe df column names after deleting new_column : ['country', 'capital', 'status', 'code', 'another_new_column', 'boolean_new_value']
        country    capital    status  code  another_new_column  \
a           Ban      Dhaka  postivie   1.0                 3.0   
b           Ind      Delhi  negative   2.0                 3.0   
c            SL    Colombo  positive   3.0                 3.0   
d           NPL  Kathmundu  positive   4.0                 3.0   
e            UK     London  negative   5.0                 3.0   
f            Fr      Paris  negative   6.0                 3.0   
country     NaN        NaN       NaN   NaN                 NaN   
capital     NaN        NaN       NaN   NaN                 NaN   
status      NaN        NaN       NaN   NaN                 NaN   

        boolean_new_value         0  
a              

Index(['a', 'b', 'c', 'd', 'e', 'f', 'l', 'm'], dtype='object', name='Index')

In [4]:
#Some essentianl Functionality
#first one is reindexing . sometime we may need reindexing .

df.reindex(['d','e','a','b','c','f'])

#even we can reindex our columns using columns argument
df.reindex(columns = ['capital','country','code','status','boolean_new_value','another_new_column'])

#also you can use .loc to create new dataframe with specified arrangement
df.loc[['a','c','f'],['country','capital','status']]




'''
#These ar some other arguments of reindex function . Try these also. DO NOT SKIP . You know how to see the documentation ,right?

index : New sequence to use as index. Can be Index instance or any other sequence-like Python data structure. An
        Index will be used exactly as is without any copying.
method: Interpolation (fill) method; 'ffill' fills forward, while 'bfill' fills backward.
        fill_value Substitute value to use when introducing missing data by reindexing.
limit : When forward- or backfilling, maximum size gap (in number of elements) to fill.
tolerance : When forward- or backfilling, maximum size gap (in absolute numeric distance) to fill for inexact matches.
level Match: simple Index on level of MultiIndex; otherwise select subset of.
copy :  If True, always copy underlying data even if new index is equivalent to old index; if False, do not copy
        the data when the indexes are equivalent

'''


"\n#These ar some other arguments of reindex function . Try these also. DO NOT SKIP . You know how to see the documentation ,right?\n\nindex : New sequence to use as index. Can be Index instance or any other sequence-like Python data structure. An\n        Index will be used exactly as is without any copying.\nmethod: Interpolation (fill) method; 'ffill' fills forward, while 'bfill' fills backward.\n        fill_value Substitute value to use when introducing missing data by reindexing.\nlimit : When forward- or backfilling, maximum size gap (in number of elements) to fill.\ntolerance : When forward- or backfilling, maximum size gap (in absolute numeric distance) to fill for inexact matches.\nlevel Match: simple Index on level of MultiIndex; otherwise select subset of.\ncopy :  If True, always copy underlying data even if new index is equivalent to old index; if False, do not copy\n        the data when the indexes are equivalent\n\n"

In [5]:
#selction function
#you can access data using row index , column names or index using

#select data using columns
df['country']  # you can pass list also df[['country','code']]

#select using slicing row index
df['a':'c'] # or even you can try df[:3]

#you can merge row and columns
df[:3][:3] #first three rows with first threee collumns

#Either you can use .loc()
df.loc['a'] #row with index name or even slice

#get single value using row and column
df.loc['c','capital'] #to get only the value of row c, column capital . CHeck using df.loc[['c'],['capital']] .Also check both data type using type() . DO NOT SKIP

#You also can use .iloc() function . i only show you slicing . using iloc . Your task will be slicing using loc and access row or column or both using .iloc
df.iloc[:2,:-2] #first two row with last two columns

#you can also select data use logic
#get all the rows where code is less than 4
df[df['code'] < 4]

# we can change value of codes where code is less than 4 using .loc() fucntion otherwise we will get an warnig as slicing create a copy or view of original dataframe

df.loc[df['code']< 4,'code'] = -1






In [6]:
#you can do arithmetic using pandas like numpy

df1 = pd.DataFrame(np.arange(50).reshape(10,5),columns = list('abcde'))
df2 = pd.DataFrame(np.random.randint(10,size = (10,5)),columns = list('abcde'))

In [7]:
df1 + df2 #or df1.add(df2)

#lets add some none value
df1.loc[3,'e'] = np.nan
df2.loc[1,'c'] = np.nan


#now do addition
df1.add(df2)

#to avoid nan value , we can pass fill_value argument via arithmetic fucntion
df1.add(df2,fill_value=0)

'''
#Method Description
#you should try these function
add, radd : Methods for addition (+)
sub, rsub : Methods for subtraction (-)
div, rdiv : Methods for division (/)
floordiv, rfloordiv : Methods for floor division (//)
mul, rmul : Methods  for multiplication (*)
pow, rpow : Methods for exponentiation (**)
'''

#Even you can do arithmetic between dataframe and series

srs = df1.loc[1]
srs

df1 - srs

a     b     c     d     e
0  -5.0  -5.0  -5.0  -5.0  -5.0
1   0.0   0.0   0.0   0.0   0.0
2   5.0   5.0   5.0   5.0   5.0
3  10.0  10.0  10.0  10.0   NaN
4  15.0  15.0  15.0  15.0  15.0
5  20.0  20.0  20.0  20.0  20.0
6  25.0  25.0  25.0  25.0  25.0
7  30.0  30.0  30.0  30.0  30.0
8  35.0  35.0  35.0  35.0  35.0
9  40.0  40.0  40.0  40.0  40.0

In [8]:
#Mapping
#THIS IS IMPORTANT . DO NOT SKIP

#we can perform numpy's element wise operations to pandas too .
#like
np.maximum(df1['a'],df1['b'])

#BUT WE CAN USE HERE Apply function to
lmda = lambda x : max(x['a'],x['b'])

df1.apply(lmda,axis = 1)

#to get differnce between max and min of each column will be
df1.apply(lambda x : x.max()-x.min())

#You can also use map() for series
#like get greater than 10 values .

df1['a'].map(lambda x : max(x,10))

0    10
1    10
2    10
3    15
4    20
5    25
6    30
7    35
8    40
9    45
Name: a, dtype: int64

In [9]:
#Sorting dataframe

#you can sort indexs using sort_index() function
#as our dataframe df1 both index are sorted , we tried to sort our columns in descending order .
#try_sort index in both axis for an unsorted dataframe . DON'T SKIP
u_df = pd.DataFrame(np.random.randint(30,size = (5,5)),columns = list('abcde'))
u_df.sort_index(axis = 1 , ascending =False)

#we can either sort column values . only sorted c and d col

u_df.sort_values(by = ['c','d'])

#you also can rank dataframe using rank() . you can change method to max,average ,min,first,dense . and changis axis = 1 will do same thing but column wise
u_df.rank(method = "min",axis = 0)


a    b    c    d    e
0  4.0  2.0  4.0  4.0  4.0
1  2.0  5.0  5.0  3.0  2.0
2  3.0  4.0  1.0  1.0  3.0
3  4.0  1.0  3.0  5.0  1.0
4  1.0  3.0  2.0  2.0  4.0

In [10]:
#Statistical methods
#we can calculate mean , sum and so on statistical operations like numpy array
#lets calcualte mean for df1

df1.mean(axis = 0,skipna = True) #change with axis = 1 and see . skipna =True will ignore nan values . Another argument level , for hierachical indexing

#similarly you can calculate many statistical operations
#check every functions here . DO NOT SKIP

'''
count : Number of non-NA values
describe : Compute set of summary statistics for Series or each DataFrame column
min, max : Compute minimum and maximum values
argmin, argmax : Compute index locations (integers) at which minimum or maximum value obtained, respectively
idxmin, idxmax : Compute index labels at which minimum or maximum value obtained, respectively
quantile : Compute sample quantile ranging from 0 to 1
sum : Sum of values
mean : Mean of values
median : Arithmetic median (50% quantile) of values
mad : Mean absolute deviation from mean value
prod : Product of all values
var : Sample variance of values
std : Sample standard deviation of values
skew : Sample skewness (third moment) of values #see comment bellow
kurt:  Sample kurtosis (fourth moment) of values #see commnet bellow
cumsum: Cumulative sum of values
cummin, cummax : Cumulative minimum or maximum of values, respectively
cumprod : Cumulative product of values
diff : Compute first arithmetic difference (useful for time series)
pct_change: Compute percent changes
'''

#max will return the max_value but if we need index of max value we can use idxmax

df1.idxmax(axis = 0) # idxmin is similar . return min values index . you can even change axis . like max or min value's index for each row .

df1.cummax() #cummin is similar . instead of max value it will take min value into the acount
'''
In pandas, cummax() is a function that returns the cumulative maximum of a Series or DataFrame along a specified axis. This means that for each position in the dataset,
it calculates the maximum value encountered up to that position.
'''

df1.pct_change()

'''
In pandas, pct_change() is a function that computes the percentage change between the current and a prior element in a DataFrame or Series.
This function is commonly used in time series analysis to measure the rate of change of a variable over time.
'''

#Important!!!

'''
Skewness and kurtosis are statistical measures used to describe the shape of a distribution.

Skewness:

Skewness measures the asymmetry of a distribution.
Interpretation:
Zero Skewness: The distribution is symmetrical.
Positive Skewness: The right tail is longer or fatter; most data points are concentrated on the left, with a few extreme values on the right.
Negative Skewness: The left tail is longer or fatter; most data points are concentrated on the right, with a few extreme values on the left.
Example: In a dataset of exam scores where most students score between 70 and 90 but a few score below 50, the distribution would be positively skewed.

Kurtosis:

Kurtosis measures the "tailedness" of the distribution, indicating the presence of outliers.
Interpretation:
Mesokurtic (Kurtosis ≈ 3): Similar shape to a normal distribution.
Leptokurtic (Kurtosis > 3): Heavier tails and a sharper peak, indicating more frequent extreme values (outliers).
Platykurtic (Kurtosis < 3): Lighter tails and a flatter peak, indicating fewer extreme values.
Example: In a dataset of incomes where most earn around the average, but a few have very high incomes, the distribution would be leptokurtic.
'''

<ipython-input-10-17143997be96>:43: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  df1.pct_change()


'\nSkewness and kurtosis are statistical measures used to describe the shape of a distribution.\n\nSkewness:\n\nSkewness measures the asymmetry of a distribution.\nInterpretation:\nZero Skewness: The distribution is symmetrical.\nPositive Skewness: The right tail is longer or fatter; most data points are concentrated on the left, with a few extreme values on the right.\nNegative Skewness: The left tail is longer or fatter; most data points are concentrated on the right, with a few extreme values on the left.\nExample: In a dataset of exam scores where most students score between 70 and 90 but a few score below 50, the distribution would be positively skewed.\n\nKurtosis:\n\nKurtosis measures the "tailedness" of the distribution, indicating the presence of outliers.\nInterpretation:\nMesokurtic (Kurtosis ≈ 3): Similar shape to a normal distribution.\nLeptokurtic (Kurtosis > 3): Heavier tails and a sharper peak, indicating more frequent extreme values (outliers).\nPlatykurtic (Kurtosis <

In [11]:
#some other statistical method
#correlation

#we can count correaltion as a whole like .corr()
df1.corr() #will give us correlation with each column

#if we need any particular column to measure correlation with other columns .
df1.corrwith(df1.a)

#covariance
#same as correaltion , we can use cov to measure covariance for all columns
df1.cov()

#unique
df1['b'].unique() #pass a series to get unique values

#value counts
#you can get value frequency of each unique values
df1['c'].value_counts() #you also can pass dataframe

#isin
#you will get a boolear array

df1.isin([10,42,16,18,13]) #pass a sequence and check if the values is in or not by getting a boolean array  . you can pass also a series


a      b      c      d      e
0  False  False  False  False  False
1  False  False  False  False  False
2   True  False  False   True  False
3  False   True  False   True  False
4  False  False  False  False  False
5  False  False  False  False  False
6  False  False  False  False  False
7  False  False  False  False  False
8  False  False   True  False  False
9  False  False  False  False  False

In [12]:
df1

a   b   c   d     e
0   0   1   2   3   4.0
1   5   6   7   8   9.0
2  10  11  12  13  14.0
3  15  16  17  18   NaN
4  20  21  22  23  24.0
5  25  26  27  28  29.0
6  30  31  32  33  34.0
7  35  36  37  38  39.0
8  40  41  42  43  44.0
9  45  46  47  48  49.0

In [13]:
#Pandas file reading functions

'''
read_csv: Still available and commonly used to read delimited data using commas.
read_table: Still available, used for reading tab-separated data.
read_fwf: Still available, used for reading fixed-width formatted text files.
read_clipboard: Still available, allowing data to be copied from the clipboard.
read_excel: Still available, used for reading Excel files (XLS and XLSX).
read_hdf: Still available for reading HDF5 files created by pandas.
read_html: Still available, used to parse tables from HTML documents.
read_json: Still available for reading JSON-formatted data.
read_msgpack: This function was removed in version 1.0.0.
read_pickle: Still available for loading Python pickled objects.
read_sas: Still available for reading SAS datasets.
read_sql: Still available for reading SQL queries into pandas DataFrames.
read_stata: Still available for reading Stata files.
read_feather: Still available for reading Feather format files.
'''

#These are the function for reading files and create DataFrame Using Pandas

'\nread_csv: Still available and commonly used to read delimited data using commas.\nread_table: Still available, used for reading tab-separated data.\nread_fwf: Still available, used for reading fixed-width formatted text files.\nread_clipboard: Still available, allowing data to be copied from the clipboard.\nread_excel: Still available, used for reading Excel files (XLS and XLSX).\nread_hdf: Still available for reading HDF5 files created by pandas.\nread_html: Still available, used to parse tables from HTML documents.\nread_json: Still available for reading JSON-formatted data.\nread_msgpack: This function was removed in version 1.0.0.\nread_pickle: Still available for loading Python pickled objects.\nread_sas: Still available for reading SAS datasets.\nread_sql: Still available for reading SQL queries into pandas DataFrames.\nread_stata: Still available for reading Stata files.\nread_feather: Still available for reading Feather format files.\n'

In [14]:


#creating a sample csv
import pandas as pd

# Creating a sample DataFrame for hierarchical indexing
data = {
    'Country': ['USA', 'USA', 'USA', 'Canada', 'Canada', 'Canada', 'Mexico', 'Mexico', 'Mexico', 'Germany', 'Germany', 'Germany', 'France', 'France', 'France', 'Italy', 'Italy', 'Italy', 'Japan', 'Japan'],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Toronto', 'Vancouver', 'Montreal', 'Mexico City', 'Guadalajara', 'Tijuana', 'Berlin', 'Munich', 'Frankfurt', 'Paris', 'Lyon', 'Marseille', 'Rome', 'Milan', 'Naples', 'Tokyo', 'Osaka'],
    'Population': [8000000, 4000000, 2700000, 2800000, 600000, 1700000, 9000000, 1500000, 1600000, 3500000, 1500000, 700000, 2100000, 500000, 850000, 2800000, 1300000, 960000, 14000000, 9000000],
    'GDP': [1700, 1040, 689, 332, 142, 159, 400 , 128, 100, 500, 330, 250, 801, 245, 190, 500, 400, 290, 2200, 1600],
    'Area': [780, 1300, 606, 630, 114, 431, 1495, 546, 246, 891, 310, 320, 248, 48, 241, 1285, 181, 119, 2194, 552],
    'Continent': ['North America'] * 9 + ['Europe'] * 9 + ['Asia'] * 2
}

df = pd.DataFrame(data)

# Save to CSV file
df.to_csv('sample_data.csv', index=False)

print(df.head())  # Display the first few rows of the dataframe



#creating a json file
import json

# Define the data in JSON format
data = [
    {"Country": "USA", "City": "New York", "Population": 8000000, "GDP": 1700, "Area": 780, "Continent": "North America"},
    {"Country": "USA", "City": "Los Angeles", "Population": 4000000, "GDP": 1040, "Area": 1300, "Continent": "North America"},
    {"Country": "USA", "City": "Chicago", "Population": 2700000, "GDP": 689, "Area": 606, "Continent": "North America"},
    {"Country": "Canada", "City": "Toronto", "Population": 2800000, "GDP": 332, "Area": 630, "Continent": "North America"},
    {"Country": "Canada", "City": "Vancouver", "Population": 600000, "GDP": 142, "Area": 114, "Continent": "North America"},
    {"Country": "Canada", "City": "Montreal", "Population": 1700000, "GDP": 159, "Area": 431, "Continent": "North America"},
    {"Country": "Mexico", "City": "Mexico City", "Population": 9000000, "GDP": 400, "Area": 1495, "Continent": "North America"},
    {"Country": "Mexico", "City": "Guadalajara", "Population": 1500000, "GDP": 128, "Area": 546, "Continent": "North America"},
    {"Country": "Mexico", "City": "Tijuana", "Population": 1600000, "GDP": 100, "Area": 246, "Continent": "North America"},
    {"Country": "Germany", "City": "Berlin", "Population": 3500000, "GDP": 500, "Area": 891, "Continent": "Europe"},
    {"Country": "Germany", "City": "Munich", "Population": 1500000, "GDP": 330, "Area": 310, "Continent": "Europe"},
    {"Country": "Germany", "City": "Frankfurt", "Population": 700000, "GDP": 250, "Area": 320, "Continent": "Europe"},
    {"Country": "France", "City": "Paris", "Population": 2100000, "GDP": 801, "Area": 248, "Continent": "Europe"},
    {"Country": "France", "City": "Lyon", "Population": 500000, "GDP": 245, "Area": 48, "Continent": "Europe"},
    {"Country": "France", "City": "Marseille", "Population": 850000, "GDP": 190, "Area": 241, "Continent": "Europe"},
    {"Country": "Italy", "City": "Rome", "Population": 2800000, "GDP": 500, "Area": 1285, "Continent": "Europe"},
    {"Country": "Italy", "City": "Milan", "Population": 1300000, "GDP": 400, "Area": 181, "Continent": "Europe"},
    {"Country": "Italy", "City": "Naples", "Population": 960000, "GDP": 290, "Area": 119, "Continent": "Europe"},
    {"Country": "Japan", "City": "Tokyo", "Population": 14000000, "GDP": 2200, "Area": 2194, "Continent": "Asia"},
    {"Country": "Japan", "City": "Osaka", "Population": 9000000, "GDP": 1600, "Area": 552, "Continent": "Asia"}
]

# Save to a JSON file
with open('sample_data.json', 'w') as json_file:
    json.dump(data, json_file, indent=4)  # indent for pretty printing

print("Data saved to sample_data.json")



  Country         City  Population   GDP  Area      Continent
0     USA     New York     8000000  1700   780  North America
1     USA  Los Angeles     4000000  1040  1300  North America
2     USA      Chicago     2700000   689   606  North America
3  Canada      Toronto     2800000   332   630  North America
4  Canada    Vancouver      600000   142   114  North America
Data saved to sample_data.json


In [15]:
#we will only discuss about read_csv functions . You must explore all of these functions or at least maximum . Any issue or anything . You can DM me.

#to read csv files and create dataframe , pandas has read_csv method
#pd.read_csv(file_path,index_col,header,names,sep)

'''
Arguments details

path : String indicating filesystem location, URL, or file-like object
sep or delimiter:  Character sequence or regular expression to use to split fields in each row
header : Row number to use as column names; defaults to 0 (first row), but should be None if there is no header row
index_col : Column numbers or names to use as the row index in the result; can be a single name/number or a list of them for a hierarchical index
names : List of column names for result, combine with header=None
skiprows: Number of rows at beginning of file to ignore or list of row numbers (starting from 0) to skip.
na_values: Sequence of values to replace with NA.
comment: Character(s) to split comments off the end of lines.
parse_dates: Attempt to parse data to datetime; False by default. If True, will attempt to parse all columns. Otherwise can specify a list of column numbers or name to parse. If element of list is tuple or list, willcombine multiple columns together and parse to date (e.g., if date/time split across two columns).
keep_date_col: If joining columns to parse date, keep the joined columns; False by default.
converters : Dict containing column number of name mapping to functions (e.g., {'foo': f} would apply the function f to all values in the 'foo' column).
dayfirst: When parsing potentially ambiguous dates, treat as international format (e.g., 7/6/2012 -> June 7,2012); False by default.
date_parser: Function to use to parse dates.
nrows : Number of rows to read from beginning of file.
iterator: Return a TextParser object for reading file piecemeal.
chunksize: For iteration, size of file chunks.
skip_footer: Number of lines to ignore at end of file.
verbose: Print various parser output information, like the number of missing values placed in non-numeric columns.
encoding: Text encoding for Unicode (e.g., 'utf-8' for UTF-8 encoded text).
squeeze: If the parsed data only contains one column, return a Series.
thousands : Separator for thousands (e.g., ',' or '.').

'''
#our csv has nan values . so we will use na_values
#our csv has 20 rows , we will take only 15 rows
#we will skip 13 index number
na_val = {'GDP':df['GDP'].mean(),'Area':df['Area'].mean()} #taking mean of values of those columns to replace missing values if present
data = pd.read_csv('/content/sample_data.csv',na_values = na_val,nrows = 15,skiprows = [12]) #reading a csv file with expected criteria

#now we can change our index col . we can assign one or multiple columns
sin_ind_data = pd.read_csv('/content/sample_data.csv',na_values = na_val,nrows = 15,skiprows = [12],index_col = 'Continent')  #now index will be continent
sin_ind_data
#we can assign multiple columns as index
mul_ind_data = pd.read_csv('/content/sample_data.csv',na_values = na_val,nrows = 15,skiprows = [12],index_col = ['Continent','Country'])

#assign index and column names
mul_ind_data.index.names = ['level1','level2']
mul_ind_data.columns.name = 'Columns'

mul_ind_data

#to save any dataframe to csv you can use to_csv() function
#mul_ind_data.to_csv(filepath)

#DO NOT SKIP OTHER FILE READING FUNCTIONS LIKE read_excel or read_json




Columns                       City  Population   GDP  Area
level1        level2                                      
North America USA         New York     8000000  1700   780
              USA      Los Angeles     4000000  1040  1300
              USA          Chicago     2700000   689   606
              Canada       Toronto     2800000   332   630
              Canada     Vancouver      600000   142   114
              Canada      Montreal     1700000   159   431
              Mexico   Mexico City     9000000   400  1495
              Mexico   Guadalajara     1500000   128   546
              Mexico       Tijuana     1600000   100   246
Europe        Germany       Berlin     3500000   500   891
              Germany       Munich     1500000   330   310
              France         Paris     2100000   801   248
              France          Lyon      500000   245    48
              France     Marseille      850000   190   241
              Italy           Rome     2800000   500  1285

In [16]:
#i will show same using a json file . data with json file . but you have to do rest . i will just show with multi-index


mul_ind_js = pd.read_json('/content/sample_data.json',orient = 'records')
mul_ind_js.set_index(['Continent', 'Country'], inplace=True)
mul_ind_js

#you should find out all the other file reading functions

City  Population   GDP  Area
Continent     Country                                     
North America USA         New York     8000000  1700   780
              USA      Los Angeles     4000000  1040  1300
              USA          Chicago     2700000   689   606
              Canada       Toronto     2800000   332   630
              Canada     Vancouver      600000   142   114
              Canada      Montreal     1700000   159   431
              Mexico   Mexico City     9000000   400  1495
              Mexico   Guadalajara     1500000   128   546
              Mexico       Tijuana     1600000   100   246
Europe        Germany       Berlin     3500000   500   891
              Germany       Munich     1500000   330   310
              Germany    Frankfurt      700000   250   320
              France         Paris     2100000   801   248
              France          Lyon      500000   245    48
              France     Marseille      850000   190   241
              Italy           Rome     2800000   500  1285
              Italy          Milan     1300000   400   181
              Italy         Naples      960000   290   119
Asia          Japan          Tokyo    14000000  2200  2194
              Japan          Osaka     9000000  1600   552

In [17]:
#pandas with database
#here we will demo with sqlite

#as we do not have any sqldb here first we need to create
import sqlite3 as sq
query = """CREATE TABLE data(a VARCHAR(20), b VARCHAR(20),c REAL, d INTEGER);""" #query to create a table
con = sq.connect('mysqldata.sqlite') #creating a connection with a db
con.execute(query) #excuting query
con.commit() #we need to commit after each any operation




In [18]:
#now add some data to table data
data = [('Atlanta', 'Georgia', 1.25, 6),
        ('Tallahassee', 'Florida', 2.6, 3),
        ('Sacramento', 'California', 1.7, 5)]

stmt = "INSERT INTO data VALUES(?, ?, ?, ?)"

con.executemany(stmt,data)
con.commit()

In [19]:
#now we can fetch the a data using cursor and fetchrow and then add to dataframe
#that will be repetative
#so we will use sqlalchemy
import sqlalchemy as sqal
db = sqal.create_engine('sqlite:///mysqldata.sqlite') # we will create an engine using our database

#then using pd.sql , we will pass query and engine to fetch data to dataframe
sql_df = pd.read_sql('select * from data',db)
sql_df

a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5

In [20]:
#Handling Missing Data With Pandas
#we could delete missing values or NaN
#we can impute missing values by filling value instead of missing value or NaN
#let's get started

#drop missning values
data_with_nan = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                    [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])
data_with_nan

#checking with isnull
data_with_nan.isnull()

#either we could do
data_with_nan[data_with_nan.notnull()]

#we can drop rows with nan values using dropna()
#data_with_nan.dropna()
data_with_nan.dropna() #we can pass 'how' argument to tell how to delete row or column. If we pass 'all' ,only the rows or columns contain all values as nan will be dropped
#pass how = 'all' and check

#we can drop column with nan using axis = 1
data_with_nan.dropna(axis = 1)

#we can also pass an argument called 'thresh'
data_with_nan.dropna(thresh = 2) #rows or columns(based on axis) which has more than or equal number not nan values will be returned
#check changing axis



0    1    2
0  1.0  6.5  3.0
3  NaN  6.5  3.0

In [21]:
#Filling Missing values
#Dropping is not a optimal solution always
#We need to know filling missing data

#we can use fillna() methods to filling missing or nan values

#Either we can replace all nan with a constan like,
data_with_nan.fillna(0) #replacing nan with 0

#Or we can pass a dict like specifiying different value for each column
replace_val = {0:3,1:1,2:100} #dict , which contain a specified replacement value for nan for each diffrent column
data_with_nan.fillna(replace_val)

#fillna return a new object . to modify orignial dataframe we should pass 'inplace' as True
#data_with_nan.fillna(replace_val,inplace = True)

#Also we can use interpolation method as we have used in reindexing
data_with_nan.fillna(method ='ffill') #filling nan values with its forward index's value for the same column . consider [1,1] postion's nan will be replaced with [0,1] postion's value which is 6.5
#method = 'bfill' will fill the backward index's data . like [1,1] value will be replace with [2,1]'s value

#Also we can set limit , how many consecutive periods will be fill . Like limit = 1 only consecutive postion
data_with_nan.fillna(method = 'ffill' , limit = 1)

#we can do this fillna() in column wise too. like replace a nan value with its neighboring columns . depends on ffill or bfill
data_with_nan.fillna(method = 'ffill',limit = 2, axis = 1) #replacing [1,1]'s nan value with [1,0]'s value. do you get the difference with axis = 0?

#Even we can pass any aggr fucntion like mean or sum
data_with_nan.fillna(data_with_nan.mean()) #replacing every nan value with mean of each column of the dataframe



<ipython-input-21-a5072ca5c64a>:18: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data_with_nan.fillna(method ='ffill') #filling nan values with its forward index's value for the same column . consider [1,1] postion's nan will be replaced with [0,1] postion's value which is 6.5
<ipython-input-21-a5072ca5c64a>:22: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data_with_nan.fillna(method = 'ffill' , limit = 1)
<ipython-input-21-a5072ca5c64a>:25: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data_with_nan.fillna(method = 'ffill',limit = 2, axis = 1) #replacing [1,1]'s nan value with [1,0]'s value. do you get the difference with axis = 0?


0    1    2
0  1.0  6.5  3.0
1  1.0  6.5  3.0
2  1.0  6.5  3.0
3  1.0  6.5  3.0

In [34]:
#Data Transformation
#Removing duplicates from pandas

duplicated_data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'], #creating a dataframe with duplicated values
 'k2': [1, 1, 2, 3, 3, 4, 4]})

duplicated_data.duplicated() # return a boolean series with bool values . True if two row are identical
#you can also pass subset to check duplicate in columns . you can also pass list of column names
duplicated_data.duplicated(subset = ['k1'])

#you can drop duplicates data using drop_duplicate()
duplicated_data.drop_duplicates() #return a dataframe where duplicate are false

#you can drop_duplicates() for a specific column or columns
duplicated_data.drop_duplicates('k1') #return a dataframe where duplicate false for that column or columns

#additionally, drop_duplicates() by deafult keep the first observation . you can keep last observation by passing 'keep' argument as 'last'

duplicated_data.drop_duplicates('k1',keep = 'last') #get the difference?



k1  k2
4  one   3
6  two   4

In [35]:
#You can transform your data using map function tooo
#consider an example where you have to add another column k3 and values will be base one k1

#lets create dict
val_k3 = {'one':'hired','two':'not hired'} #sample assumpiton if k1 value is 'one' then k3's value will be 'hired'

#now call the map function. remember map only used for series .

#so create anoter column in the dataframe
duplicated_data['k3'] = duplicated_data['k1'].map(lambda x: val_k3[x] ) #if k1's value matching with val_k3's key , we will get the value and put to the k3 column
duplicated_data #try to visualize what has just happended here .DO NOT SKIP


k1  k2         k3
0  one   1      hired
1  two   1  not hired
2  one   2      hired
3  two   3  not hired
4  one   3      hired
5  two   4  not hired
6  two   4  not hired

In [38]:
#Value Replacing using Pandas
#we can replace a value or values using replace() method

#replace k2's 1 value with 5
duplicated_data['k2'].replace(1,5) #you can also pass a dict
duplicated_data['k2'].replace({1:5,2:6}) #to make change your original dataframe make sure inplace argument is set to True as this method shows you a copy and original dataframe is not modified unless you set the value True
#if you want to change more values with a single value please use list
#like .replace([1,2],0) or even can pass replacement values as a list too
#like .replace([1,2],[4,6])
#Try these and explore .DO NOT SKIP


0    5
1    5
2    6
3    3
4    3
5    4
6    4
Name: k2, dtype: int64

In [52]:
#Index Re-naming
import numpy as np
rename_df = pd.DataFrame(np.random.randn(9).reshape(3,3),index = ['one','two','three'],columns = ['col1','col2','col3'])
rename_df
#if you want to change in original dataframe using .map()
rename_df.index = rename_df.index.map(lambda x: x[:4].upper()) #try change the columns names . DO NOT SKIP
rename_df


#you can change with rename function also to get a copy
rename_df.rename(index = str.title,columns = str.upper) #see the  change

#using this method you can change your columns and index names too
rename_df.rename(index = {'ONE':'five'},columns = {'col1':'new_col'}) #get it ? Even you can chnage multiple columns and indexs names too. Try.



new_col      col2      col3
five  0.432827 -0.665375  0.647059
TWO   2.416367  0.455220 -0.433345
THRE -2.532634  0.353006 -1.813839

In [74]:
#categorized data using pandas bining
#let's take an example
#create a dataframe with marks
#let's define a category range as bin

marks = np.random.randint(33,100,size =10)
marks_df = pd.DataFrame({'mark':marks})
bin = [33,60,70,80,100]
label = ['Pass','C','B','A']

#marks_df['range'] = pd.cut(marks_df['mark'],bin,label) #passing values must be 1D . You can also pass right  = False and check what happend

pd.cut(marks_df['mark'],bins = bin)#pass with labels = label and check . For float data you also can pass precision argument to set how many digits you want after decimal point


0     (60, 70]
1    (80, 100]
2     (33, 60]
3     (60, 70]
4     (33, 60]
5     (33, 60]
6     (33, 60]
7    (80, 100]
8    (80, 100]
9     (60, 70]
Name: mark, dtype: category
Categories (4, interval[int64, right]): [(33, 60] < (60, 70] < (70, 80] < (80, 100]]

In [91]:
#Filtering outliers with Pandas
outlier_data = pd.DataFrame(np.random.randn(300,4))
outlier_data.head()
outlier_data.describe() #see the stat of the dataframe

#suppose we will filter all rows where minimu one value is greater than 4 or -4
outlier_data[(outlier_data.abs() > 2).any(axis = 1)] #we have to find values for each column , hence we have to pass axis = 1 , otherwise we will get a mismatch error
#why ? (outlier_data.abs() > 2).any() to see the boolearn series
#(outlier_data.abs() > 2).any() #see with axis = 1 and you will understand

#using this technique you can filter and drop or do any oeprations with your data


0         1         2         3
2    2.707216 -0.942044 -0.641186  0.834523
7    2.158543 -0.388273 -1.132604  0.274054
14  -1.279401 -0.169095 -2.069954  0.221526
15  -2.440389  0.095232  0.211487 -0.778066
16   0.497259 -0.909433 -0.573693  2.062392
23  -0.988342 -0.727472 -2.090047 -0.536509
33   0.451601  2.586449  1.477345 -0.348069
37  -2.573053  0.002002 -1.140165  0.576854
38  -0.804417  0.847692 -2.258184  0.912484
43   0.530717 -1.986015  2.197828  1.728423
45  -0.073269 -2.153196 -0.581294 -1.242528
49   2.172989 -1.315704  0.862425 -0.117422
50  -0.183820 -2.139560 -0.635325  0.482376
51   3.144235  0.517400  1.112102  0.770359
54  -3.252608 -0.119864 -0.665735 -1.027712
61   3.166690 -0.270337  0.915035  0.148882
70   0.227454 -2.438394 -0.837988 -1.540990
75   1.163349  1.221838  0.231943 -2.232261
83   2.663799 -0.010816  0.470640  0.004536
84  -0.229204  0.042827 -1.466665 -2.051926
85  -2.916118  0.059614  0.333445 -0.389221
87  -2.333868 -0.830303  0.553214 -1.006923
89  -2.112087 -0.724081  0.263487 -0.607496
90   0.726838 -0.159588  0.929387 -2.668040
100 -2.326951  1.212847 -1.422428  0.194385
106  2.518322  0.231408 -0.290354  1.380184
111  1.686583  2.184785  1.520065 -0.172774
112 -2.020472  0.871949 -1.596504  1.197028
114  1.537513 -0.261414 -1.071774 -2.656789
117 -1.753372 -0.402475  1.456333  2.986694
126  0.106904  0.359197 -0.800777 -2.067340
133 -1.283298  0.831875  2.423026  0.140018
140 -0.877830  0.604669 -2.059358 -0.305716
148  0.931561  2.022542  1.341329 -0.403019
168  2.945694 -0.646436  0.373146 -0.981306
184 -2.476036 -0.484616 -1.787650 -1.700039
186  0.095584  0.641309 -2.195833  0.864936
206  2.100996 -0.359710  0.679017  0.328392
226  0.691606 -1.279251 -2.119534 -0.538331
231 -0.024053  0.257718  2.072540 -1.507194
239  0.854009 -0.007935  2.575662  2.504381
264 -0.952518 -0.611908  2.348683 -1.218758
272  0.829322 -0.142280  2.605493  0.585165
278 -2.266557  1.254635 -0.125172 -1.215345
291 -2.480857  0.840090 -1.002140  0.244529
295  1.741238  0.394748  2.700568  0.325698
299  2.513106  0.796603  1.084429  1.150372

In [97]:
#Random sampling and Permutation

#you can randomly sample your dataframe using sample() method

outlier_data.sample(10) #taking randomly 10 rows . you can try different number

#Also you can rearrange using permutation
per = np.random.permutation(5) #randomly permutation 0 -5
per

#now pass the permutation to the dataframe via take()
outlier_data.take(per)


0         1         2         3
4 -1.112188  0.992634 -0.920520 -0.066333
0 -1.012329 -1.263064 -0.552833  0.176318
3 -0.734267 -0.716143 -0.067868  0.222259
1  1.234288 -1.663691  0.058463 -0.565235
2  2.707216 -0.942044 -0.641186  0.834523

In [100]:
#Addtinal , you can use pandas get_dummies to create a simple one-hot encoding

dummy_df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],'data1': range(6)})
dummy_df

#generate one-hot encoding for key column
pd.get_dummies(dummy_df['key'],prefix = 'key').replace({False:0,True:1})


key_a  key_b  key_c
0      0      1      0
1      0      1      0
2      1      0      0
3      0      0      1
4      1      0      0
5      0      1      0

In [116]:
#Pandas String Manipulation
#python is very hadny to work with strings

string = 'hello, world, is , universal'

#we can split with a separator
print(f"with a comma separator we can split '{string}' to a list like {string.split(',')}")
#also we can remove whitespaces
words = [x.strip() for x in string.split(',')]
print(f"after removing whitespace using strip() words are now {words}")

#we can join words
print(f"Even we can join our words like {' '.join(words)}")

#we can check substring
'hel' in string

#we can find index of substrings
string.index(',') #try any substring which is present unless you will get an error

#To avoid this error we also can use find() . if any substring is not present it will return -1 instead raise an error
string.find(':') #do same thing with index and check what happend

#we can replace strings
string.replace('hel' , 'HEL') #get your hands dirty with some more practices . DO NOT SKIP

#Even we can count occrences of sub strings in the string
string.count('l')

#string related functions with description. We have tried some but you should explore all of them
#explore them by yourself
#DO NOT SKIP
'''
count  :Return the number of non-overlapping occurrences of substring in the string.
endswith : Returns True if string ends with suffix.
startswith : Returns True if string starts with prefix.
join : Use string as delimiter for concatenating a sequence of other strings.
index: Return position of first character in substring if found in the string; raises ValueError if not found.
find : Return position of first character of first occurrence of substring in the string; like index, but returns –1 if not found.
rfind Return position of first character of last occurrence of substring in the string; returns –1 if not found.
replace : Replace occurrences of string with another string.
strip,rstrip,lstrip: Trim whitespace, including newlines; equivalent to x.strip() (and rstrip, lstrip, respectively)for each element.
split : Break string into list of substrings using passed delimiter.
lower : Convert alphabet characters to lowercase.
upper : Convert alphabet characters to uppercase.
casefold : Convert characters to lowercase, and convert any region-specific variable character combinations to acommon comparable form.
ljust,rjust : Left justify or right justify, respectively; pad opposite side
'''

with a comma separator we can split 'hello, world, is , universal' to a list like ['hello', ' world', ' is ', ' universal']
after removing whitespace using strip() words are now ['hello', 'world', 'is', 'universal']
Even we can join our words like hello world is universal


4

In [119]:
#regular expressions with python

import re

#let's us split using re . spliting words with variable whitespaces
s = "hello  \t world   is     universal" #sample string

re.split('\s+',s)
#it will first compile our expression and then do the split operations . In case you need huge usage of same pattern you do not need to compile it again and agiain
#to save time for your program . you can complie once and perform task how many times you need

regex = re.compile('\s+') #compile your patter first

#use it to split
regex.split(s)

#for other strings too
regex.split('HELLO world       Is   universal tooo ')

'''
explore a bit more using re

findall : Return all non-overlapping matching patterns in a string as a list
finditer : Like findall, but returns an iterator
match : Match pattern at start of string and optionally segment pattern components into groups; if the patternmatches, returns a match object, and otherwise None
search : Scan string for match to pattern; returning a match object if so; unlike match, the match can be anywhere inthe string as opposed to only at the beginning
split : Break string into pieces at each occurrence of pattern
sub, subn : Replace all (sub) or first n occurrences (subn) of pattern in string with replacement expression; use symbols\1, \2, ... to refer to match group elements in the replacement string
'''

['HELLO', 'world', 'Is', 'universal', 'tooo', '']

In [129]:
#pandas with string

s_data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com', 'Rob': 'rob@gmail.com', 'Wes': np.nan}

st_df = pd.Series(s_data)
st_df
st_df.isnull()

#checking contain 'mail' substirng or not

st_df.str.contains('mail')

#finding pattern also
pattern = '([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'
st_df.str.findall(pattern,flags = re.IGNORECASE)

#instead you can find a boolean array
st_df.str.match(pattern,flags =re.IGNORECASE)


#functions we should explore

'''
#access through the str. accessor

cat : Concatenate strings element-wise with optional delimiter
contains : Return boolean array if each string contains pattern/regex
count : Count occurrences of pattern
extract: Use a regular expression with groups to extract one or more strings from a Series of strings; the result will be a DataFrame with one column per group
endswith : Equivalent to x.endswith(pattern) for each element
startswith: Equivalent to x.startswith(pattern) for each element
findall : Compute list of all occurrences of pattern/regex for each string
get : Index into each element (retrieve i-th element)
isalnum: Equivalent to built-in str.alnum
isalpha :Equivalent to built-in str.isalpha
isdecimal: Equivalent to built-in str.isdecimal
isdigit: Equivalent to built-in str.isdigit
islower: Equivalent to built-in str.islower
isnumeric: Equivalent to built-in str.isnumeric
isupper: Equivalent to built-in str.isupper
join :Join strings in each element of the Series with passed separator
len :Compute length of each string
lower, upper : Convert cases; equivalent to x.lower() or x.upper() for each element
match: Use re.match with the passed regular expression on each element, returning matched groups as list
pad : Add whitespace to left, right, or both sides of strings
center: Equivalent to pad(side='both')
repeat : Duplicate values (e.g., s.str.repeat(3) is equivalent to x * 3 for each string)
replace : Replace occurrences of pattern/regex with some other string
slice : Slice each string in the Series
split : Split strings on delimiter or regular expression
strip  :Trim whitespace from both sides, including newlines
rstrip : Trim whitespace on right side
lstrip  :Trim whitespace on left side
'''

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object

In [167]:
#Combination,reshaping with Pandas

#Hierarchicahl Indexing
#we have seen hierarchical indexing earlier
#Now we will acessig data with hierarchical indexing
#if you have done this ,SKIP
#recalling our mul_ind_data
mul_ind_data
#checking index
mul_ind_data
#acessing data using outer level
mul_ind_data.loc['North America']
#aceesing data using both index
mul_ind_data.loc['North America','Mexico']

#We can swap levels using swaplevel()
mul_ind_data.swaplevel('level1','level2') #or we can pass swaplevel(0,1)

#we can sort level wise
mul_ind_data.sort_index(level = 'level2') #or even we can pass level = 1

#sorting with outer_level
mul_ind_data.sort_index(level = 'level1') #or we can pass level = 0

#can you do both the action swaplevel and sort at a time?
#This is your chalange . DO NOT SKIP

<ipython-input-167-0cd1b1e41080>:14: PerformanceWarning: indexing past lexsort depth may impact performance.
  mul_ind_data.loc['North America','Mexico']


Columns                       City  Population   GDP  Area
level1        level2                                      
Europe        France         Paris     2100000   801   248
              France          Lyon      500000   245    48
              France     Marseille      850000   190   241
              Germany       Berlin     3500000   500   891
              Germany       Munich     1500000   330   310
              Italy           Rome     2800000   500  1285
North America Canada       Toronto     2800000   332   630
              Canada     Vancouver      600000   142   114
              Canada      Montreal     1700000   159   431
              Mexico   Mexico City     9000000   400  1495
              Mexico   Guadalajara     1500000   128   546
              Mexico       Tijuana     1600000   100   246
              USA         New York     8000000  1700   780
              USA      Los Angeles     4000000  1040  1300
              USA          Chicago     2700000   689   606

In [181]:
#you can calculate summary statistics using level
#like sum or mean
mul_df = pd.DataFrame(np.random.randint(100,size = (6,6)),index = [['a','a','b','b','c','c'],[1,2,3,4,5,6]],columns =list('ijklmn'))
mul_df.groupby(level = 0).sum()
#but we will explore groupby later


i    j   k    l    m    n
a  109  190  53  107   79   93
b  133   86  56  110   68  126
c  149   92  30  124  146  108

In [182]:
#we can set index any column
mul_df.set_index('i') #drop = False will keep that column too

#we can also reset index by reset_index()
#mul_df.reset_index()


j   k   l   m   n
i                     
20  97  39  23  61  49
89  93  14  84  18  44
94   9  46  33   6  65
39  77  10  77  62  61
99   9  23  36  49  92
50  83   7  88  97  16

In [186]:
#merging dataframe
#we can perform join operation like sql using merge() function
#Even using both column not necessarily the same name . I mean even if the names are different , we can handle

#consider two dataframe with a common column first
mer_df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],'data1': range(7)})
mer_df2 = pd.DataFrame({'key': ['a', 'b', 'd'],'data2': range(3)})

#as the both have key column , we can perform a merge on key
mer_df1.merge(mer_df2,on='key',how ='outer') #outer join with two dataframe

#Now if they do not have same column , still we can perform merge
mer_df3 = pd.DataFrame({'k': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],'data1': range(7)})
mer_df4 = pd.DataFrame({'key': ['a', 'b', 'd'],'data2': range(3)})

mer_df3.merge(mer_df4,left_on='k',right_on ='key',how = 'outer') #we will specify columns using left_on and right_on for left and right df respectively

'''
Param of how will be ,

'inner' : Use only the key combinations observed in both tables
'left' : Use all key combinations found in the left table
'right': Use all key combinations found in the right table
'output': Use all key combinations observed in both tables together
'''

#we can even merge on indexes or colunm with index
#we can make right dataframe's index to key using right_index = True and for using left dataframe's index to key, left_index = True

left1 = pd.DataFrame({'key': ['a', 'b', 'a', 'a', 'b', 'c'],'value': range(6)})
right1 = pd.DataFrame({'group_val': [3.5, 7]}, index=['a', 'b'])

#using left1's key and right1's index
left1.merge(right1,left_on ='key',right_index = True, how  ='inner')

#your task is to join using both dataframe's index
#code here






#Or let me know . I will provide later notebook
#if you want to join on index only , you also can use join() function

left2 = pd.DataFrame([[1., 2.], [3., 4.], [5., 6.]],index=['a', 'c', 'e'],columns=['Ohio', 'Nevada'])
right2 = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [13, 14]],index=['b', 'c', 'd', 'e'],columns=['Missouri', 'Alabama'])

left2.join(right2,how = 'inner')

#we can join() even columns using on
#even you can join() a list of dataframe using a list of dataframe like .join([dataframe_one,dataframe_two])


Ohio  Nevada  Missouri  Alabama
c   3.0     4.0       9.0     10.0
e   5.0     6.0      13.0     14.0

In [201]:
#concatenation using dataframe
#we can concatenate multiple dataframe on both axis
#we cna concatenate dataframe with series on both axis
#we can concatenate multiple series on both axis

#concatenation two dataframe


# Create the first DataFrame
df1 = pd.DataFrame({
    'A': [1, 2],
    'B': [3, 4]
})

# Create the second DataFrame
df2 = pd.DataFrame({
    'A': [5, 6],
    'B': [7, 8]
})

# Concatenate along rows
pd.concat([df1, df2], axis=0)

#even we can concatenate along columns
pd.concat([df1,df2],axis = 1)


#we can concatenate a seires with dataframe too
# Create a Series
s = pd.Series([11,12],name = 'C')
pd.concat([df1,s])

#along axis
pd.concat([df1,s],axis = 1)

A  B   C
0  1  3  11
1  2  4  12

In [202]:
#Groupby in Pandas

import pandas as pd

# Sample DataFrame
data = {
    'Salesperson': ['Alice', 'Bob', 'Alice', 'Bob', 'Alice', 'Bob', 'Alice', 'Bob'],
    'Region': ['East', 'West', 'East', 'West', 'East', 'West', 'East', 'West'],
    'Quarter': ['Q1', 'Q1', 'Q2', 'Q2', 'Q3', 'Q3', 'Q4', 'Q4'],
    'Sales': [200, 180, 220, 210, 230, 190, 240, 200]
}

# Create DataFrame and set multi-index with Salesperson and Region
df = pd.DataFrame(data)
df.set_index(['Salesperson', 'Region'], inplace=True)  # Setting a multi-index for later grouping
print("Initial DataFrame with multi-index:\n", df, "\n")

# Example 1: Group by 'Quarter' and sum the sales for each quarter
grouped_by_quarter = df.groupby('Quarter').sum()
print("Total sales for each quarter:\n", grouped_by_quarter, "\n")

# Example 2: Group by 'Salesperson' and 'Region' using multi-index and sum sales
grouped_by_salesperson_region = df.groupby(level=['Salesperson', 'Region']).sum()
print("Total sales by Salesperson and Region:\n", grouped_by_salesperson_region, "\n")

# Example 3: Group by 'Quarter' and 'Region' and calculate mean sales for each group
grouped_by_quarter_region = df.groupby(['Quarter', 'Region']).agg({'Sales': 'mean'})
print("Mean sales by Quarter and Region:\n", grouped_by_quarter_region, "\n")

# Example 4: Group by 'Quarter' with as_index=False to avoid setting 'Quarter' as the index in the result
grouped_no_index = df.groupby(['Quarter'], as_index=False).sum()
print("Total sales by Quarter without setting 'Quarter' as index:\n", grouped_no_index, "\n")

# Example 5: Group by 'Salesperson' (using index level) and sum sales
grouped_by_salesperson = df.groupby(level='Salesperson').sum()
print("Total sales by Salesperson:\n", grouped_by_salesperson)


Initial DataFrame with multi-index:
                    Quarter  Sales
Salesperson Region               
Alice       East        Q1    200
Bob         West        Q1    180
Alice       East        Q2    220
Bob         West        Q2    210
Alice       East        Q3    230
Bob         West        Q3    190
Alice       East        Q4    240
Bob         West        Q4    200 

Total sales for each quarter:
          Sales
Quarter       
Q1         380
Q2         430
Q3         420
Q4         440 

Total sales by Salesperson and Region:
                      Quarter  Sales
Salesperson Region                 
Alice       East    Q1Q2Q3Q4    890
Bob         West    Q1Q2Q3Q4    780 

Mean sales by Quarter and Region:
                 Sales
Quarter Region       
Q1      East    200.0
        West    180.0
Q2      East    220.0
        West    210.0
Q3      East    230.0
        West    190.0
Q4      East    240.0
        West    200.0 

Total sales by Quarter without setting 'Quarter' as ind